### ISSUE TITLE
Is there any license I should add when redistributing this code?

### ISSUE THREAD

**Issue by roelandp** [graphenepay/graphenepay-dev#1]
Hi! Thanks for this. What license does this code have? I'm curious if i can redistribute this code. 

I noticed that graphenejs liberary (https://github.com/graphenepay/graphenepay-dev/blob/master/public/js/graphenejs.js) is the steemjs library by @adcpm (with basic unminified applied, see https://github.com/adcpm/steem/blob/dev/dist/steem.min.js) I think? 

I noticed @adcpm has his contents distributed as MIT licensed, however I think that means it should be included in this software as well? Does this mean this software is MIT licensed too?

Please let me know. Thx @graphenepay!

**Comment by graphenepay** [comment]
This software is released under the MIT license as described in https://github.com/graphenepay/graphenepay-dev/blob/master/license.md
